platform :ios, '9.0'

target 'ActionableHealth' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    pod 'Alamofire','3.5.1'
    pod 'TPKeyboardAvoiding'
    pod 'HCSStarRatingView'
    pod 'DAKeyboardControl'
    pod 'SDWebImage'
    pod 'APAddressBook'
    pod 'PhoneNumberKit','0.8.5'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'

    target 'ActionableHealthTests' do
        inherit! :search_paths
        # Pods for testing
    end

    target 'ActionableHealthUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
