platform :ios, ‘8.0’

target 'ActionableHealth' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire'
    pod 'TPKeyboardAvoiding'
    pod 'HCSStarRatingView'
    pod 'DAKeyboardControl'

  target 'ActionableHealthTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ActionableHealthUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
